language: php

php:
  - '5.6'
  - '7.2'

install:
  - composer install

script:
  - composer lint

# Pull requests are built by default.
branches:
  only:
  - master

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache
